# Generated by Django 2.1.2 on 2018-10-23 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(default='Insert deal description here')),
                ('RRP', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('tippingPoint', models.IntegerField(default=0)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0))),
                ('pic', models.CharField(default='http://trotters-van-hire.co.uk/wp-content/uploads/2016/11/DelBoyVan.jpg', max_length=500)),
            ],
        ),
    ]
